print('hello world')
for n=1, 10 do
    print(n)
end

-- local t = {math.random(),math.random(),math.random(),math.random(),math.random(),math.random()} table.sort(t) function x(a,b,c,d,e) for a,b in c(), d(), e() do if math.random() >= math.random() then break else continue end if math.random() then a = f() end if a >= math.random and b >= a * math.random() ^ 2 then break elseif b >= math.random and a <= b * math.random ^ 3 then return else continue end continue end if a > b and b > a or a > d and a > math.random() then return a, b, c else return c, d, e end end x(a,b,c,d,t)